version: '3.7',
services:
  web:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://apppetsaojoao@postgres/petsaojoao
  postgres:
    image: postgres:9.6.17-alpine
    environment:
      POSTGRES_USER: petsaojoao
      POSTGRES_DB: psjdb
